[phases]
  [phases.setup]
  command = "npm install -g npm@latest"

[build]
  command = "npm install --prefix therapy-app && npm run build --prefix therapy-app && cd ../backend && npm install"

[start]
  command = "node backend/server.js"

[variables]
  NODE_VERSION = "18"
