[phases]
  [phases.setup]
  command = "corepack enable && corepack prepare npm@latest --activate"

[build]
  command = "cd therapy-app && npm install && npm run build && cd ../backend && npm install"

[start]
  command = "npm run start"

[variables]
  NODE_VERSION = "18"
