[phases]
  [phases.setup]
  command = "corepack enable && corepack prepare npm@latest --activate"

  [phases.build]
  command = "cd frontend && npm install && npm run build && cd ../backend && npm install"

[start]
  command = "node backend/server.js"

[variables]
  NODE_VERSION = "18"
  PORT = "5000"
