[phases]
  [phases.setup]
  command = "npm install -g npm@latest"  # Ensure npm is updated

[build]
  command = "npm install --prefix backend"  # Install only backend dependencies

[start]
  command = "node backend/server.js"  # Start the backend server

[variables]
  NODE_VERSION = "18"
